import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#F1F0F2',
    flex: 1,
  },
  StaticContainer: {
    marginTop: 1,
    backgroundColor: '#FFFFFF',
  },
  StatisticText: {
    fontSize: 26,
    marginTop: 18,
    alignSelf: 'center',
    marginRight: 'auto',
    marginLeft: 40,
    marginBottom: 25,
  },
  today: {
    fontSize: 17,
    marginTop: 28,
    alignSelf: 'center',
    marginRight: 'auto',
    marginLeft: 52,
    marginBottom: 5,
  },
  cal: {
    fontSize: 24,
    marginTop: 0,
    alignSelf: 'center',
    marginRight: 'auto',
    marginLeft: 52,
    marginBottom: 14,
  },
  dot: {
    fontSize: 19,
    color: '#259BB1',
  },
  Goal: {
    fontSize: 15,
    marginTop: 0,
    alignSelf: 'center',
    marginBottom: 0,
  },
  todaycal: {
    fontSize: 52,
    alignSelf: 'center',
    marginTop: 18,
    marginBottom: 0,
  },
  pgbarPercentText: {
    marginLeft: 10,
    color: '#352641',
    fontSize: 14,
    marginTop: 40,
  },
  pgbarPercentText2: {
    marginLeft: 73,
    marginRight: 67,
    alignSelf: 'center',
    color: '#1C1C1C',
    fontSize: 13,
    marginTop: 30,
  },
  pgbarPercentText3: {
    marginLeft: 0,
    marginRight: 75,
    alignSelf: 'center',
    color: '#1C1C1C',
    fontSize: 13,
    marginTop: 30,
  },
  pgbarPercentText4: {
    marginLeft: 0,
    marginRight: 'auto',
    alignSelf: 'center',
    color: '#1C1C1C',
    fontSize: 13,
    marginTop: 30,
  },
  pgbarPercentText5: {
    marginLeft: 70,
    marginRight: 0,
    alignSelf: 'center',
    color: '#1C1C1C',
    fontSize: 13,
    marginTop: 10,
  },
  pgbarPercentText6: {
    marginLeft: 55,
    marginRight: 0,
    alignSelf: 'center',
    color: '#1C1C1C',
    fontSize: 13,
    marginTop: 10,
  },

  pgbarPercentText7: {
    marginLeft: 60,
    marginRight: 0,
    alignSelf: 'center',
    color: '#1C1C1C',
    fontSize: 13,
    marginTop: 10,
  },
  comment: {
    fontSize: 12,
    color: '#71677A',
    marginTop: 5,
    marginRight: 20,
    marginLeft: 19,
  },
  filterContainer: {
    marginTop: 14,
    flex: 1,
    flexDirection: 'row',
  },
  filterImage: {
    marginLeft: 20,
    width: 19.8,
    height: 19.8,
    marginBottom: 0,
    alignContent: 'center',
    resizeMode: 'contain',
    marginRight: 7,
  },
  filterText: {
    fontSize: 13,
    marginLeft: 0,
  },
  dayContainer: {
    backgroundColor: '#F1F0F2',
    marginTop: 0,
    height: 50,
  },
  dayText: {
    fontSize: 17,
    marginLeft: 'auto',
    marginRight: 'auto',
    alignContent: 'center',
    marginTop: 20,
  },
});
